In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

import sys
sys.path.append('../')

from src.logistic_regression import LogisticRegression
from src.optimizers import SGD, Adagrad, Adam

In [3]:
X = np.array([[0, 1], [1, 0], [1, 1]])
y = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

In [4]:
logistic_regression = LogisticRegression()
logistic_regression.fit(X, y, epochs=10000, batch_size=2, optimizer=SGD(lr=1e-2))

  0%|          | 0/10000 [00:00<?, ?it/s]

100%|██████████| 10000/10000 [00:03<00:00, 2633.35it/s, loss=0.0705]


In [6]:
pred = logistic_regression.predict(X)
print(pred)

[[0.00243845 0.95160769 0.04595386]
 [0.9505372  0.00225463 0.04720818]
 [0.03447411 0.03340757 0.93211832]]
